### PR TITLE
Setting up unit tests

### PR DESCRIPTION
**Pull request by MonssafToukal**

### CODE REVIEW

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by MonssafToukal** [comment]
Ok, the test failed because the environment variable `GUROBI_HOME` does not exist for the Jenkins' user.

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
